In [1]:
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
from torch import optim

from torch.autograd import Variable

from data import iris

criterion = nn.CrossEntropyLoss()

In [2]:
class IrisNet(nn.Module):
    def __init__(self, input_size, hidden1_size, hidden2_size, num_classes):
        
        super(IrisNet, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden1_size)
        self.relu1 = nn.ReLU()
        self.fc2 = nn.Linear(hidden1_size, hidden2_size)
        self.relu2 = nn.ReLU()
        self.fc3 = nn.Linear(hidden2_size, num_classes)
    
    def forward(self, x):
        out = self.fc1(x)
        out = self.relu1(out)
        out = self.fc2(out)
        out = self.relu2(out)
        out = self.fc3(out)
        return out

In [3]:
model = IrisNet(4, 6, 50, 3)
optimizer = optim.SGD(model.parameters(), lr=0.01)
num_epochs = 100
print(model)

IrisNet(
  (fc1): Linear(in_features=4, out_features=6, bias=True)
  (relu1): ReLU()
  (fc2): Linear(in_features=6, out_features=50, bias=True)
  (relu2): ReLU()
  (fc3): Linear(in_features=50, out_features=3, bias=True)
)


In [4]:
batch_size = 60
iris_data_file = "data/iris.data.txt"

In [1]:
train_ds, test_ds = iris.get_datasets(iris_data_file)

NameError: name 'iris' is not defined

In [7]:
train_loader = torch.utils.data.DataLoader(dataset=train_ds, batch_size = batch_size, shuffle=True)

In [8]:
test_loader = torch.utils.data.DataLoader(dataset=test_ds, batch_size = batch_size, shuffle = True)

In [9]:
for i in range(num_epochs):
    cum_loss = 0
    for inputs, labels in train_loader:
        optimizer.zero_grad()
        output = model.forward(inputs)
#         output = output.long()
#         print(output)
        loss = criterion(output, labels.long())
        loss.backward()
        optimizer.step()
        
        cum_loss += loss.item()
        
    print("Training loss: ", cum_loss / len(train_loader))

Training loss:  1.128388226032257
Training loss:  1.0949336290359497
Training loss:  1.0731183290481567
Training loss:  1.0571289658546448
Training loss:  1.0431751012802124
Training loss:  1.0328028202056885
Training loss:  1.0205643773078918
Training loss:  1.0103479027748108
Training loss:  1.0020192563533783
Training loss:  0.9913573265075684
Training loss:  0.9818470478057861
Training loss:  0.9700731039047241
Training loss:  0.9602098166942596
Training loss:  0.9540480375289917
Training loss:  0.9412203729152679
Training loss:  0.9309024512767792
Training loss:  0.925045520067215
Training loss:  0.9112565219402313
Training loss:  0.9030390977859497
Training loss:  0.893351137638092
Training loss:  0.8838623464107513
Training loss:  0.8753636479377747
Training loss:  0.8641993701457977
Training loss:  0.8548792004585266
Training loss:  0.8454445004463196
Training loss:  0.8359574973583221
Training loss:  0.8274637162685394
Training loss:  0.8178788721561432
Training loss:  0.81067

In [11]:
with torch.no_grad():
    for data, label in test_loader:
        counter = 0
        for d in data:
            print(model(d))
#         if out[label] == out.max():
#             print("Correct")
# #         print(maxPrediction)
#         maxIndicies = [i for i in range(1)]

tensor([-1.8836,  2.1516,  2.6020])
tensor([ 2.6093,  0.0337, -1.6023])
tensor([-2.4972,  2.2454,  3.0560])
tensor([-1.2531,  1.3404,  1.5295])
tensor([-1.1368,  1.6002,  1.6948])
tensor([ 2.1571,  0.1774, -1.2677])
tensor([-1.1865,  1.5431,  1.6979])
tensor([-0.2647,  1.1824,  0.8227])
tensor([-0.6678,  1.2808,  1.1456])
tensor([-1.4698,  1.6689,  1.9667])
tensor([ 2.4328,  0.0630, -1.4845])
tensor([-0.7935,  1.3429,  1.2494])
tensor([-2.1478,  2.1006,  2.7160])
tensor([ 2.2773,  0.2266, -1.2844])
tensor([ 2.9941, -0.0069, -1.8319])
tensor([-0.3516,  1.0730,  0.7760])
tensor([ 2.3606,  0.1085, -1.4168])
tensor([-0.7360,  1.4369,  1.3156])
tensor([ 2.3664,  0.0494, -1.4647])
tensor([-1.1455,  1.4495,  1.5592])
tensor([-1.3614,  1.5775,  1.7954])
tensor([ 2.5535,  0.0595, -1.5495])
tensor([-0.7556,  1.3286,  1.2366])
tensor([-2.0049,  1.8848,  2.4456])
tensor([-0.8601,  1.2374,  1.2299])
tensor([ 2.4225,  0.0968, -1.4558])
tensor([-1.0574,  1.4861,  1.5439])
tensor([ 2.6517,  0.0667, -1