In [1]:
from __future__ import print_function
import torch
import torch.nn as nn
import torch.nn.functional as F

In [39]:
x = torch.zeros(2,2, requires_grad=True)
x

tensor([[0., 0.],
        [0., 0.]], requires_grad=True)

In [44]:
y = x+2
y

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)

In [45]:
y.grad_fn

In [48]:
z = y*y*3
out = z.mean()
z, out

(tensor([[12., 12.],
         [12., 12.]], grad_fn=<MulBackward0>),
 tensor(12., grad_fn=<MeanBackward0>))

In [49]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [50]:
out.backward()

In [51]:
x.grad

tensor([[3., 3.],
        [3., 3.]])

# Neural Networks

In [3]:
import torch
import torch.nn as nn
import matplotlib.pyplot as plt

from torch.autograd import Variable

from data import iris

In [4]:
class IrisNet(nn.Module):
    def __init__(self, input_size, hidden1_size, hidden2_size, num_classes):
        
        super(IrisNet, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden1_size)
        self.relu1 = nn.ReLU()
        self.fc2 = nn.Linear(hidden1_size,hidden2_size)
        self.relu2 = nn.ReLU()
        self.fc3 = nn.Linear (hidden2_size, num_classes)
    
    def forward(self,x):
        out =self.fc1(x)
        out =self.relu1(out)
        out =self.fc2(out)
        out =self.relu2(out)
        out =self.fc3(out)
        return out

In [5]:
model = IrisNet(4,100,50,3)
print (model)

IrisNet(
  (fc1): Linear(in_features=4, out_features=100, bias=True)
  (relu1): ReLU()
  (fc2): Linear(in_features=100, out_features=50, bias=True)
  (relu2): ReLU()
  (fc3): Linear(in_features=50, out_features=3, bias=True)
)


In [7]:
batch_size = 60
iris_data = 'data/iris.data.txt'

In [11]:
#get datasets
train_ds, test_ds = iris.get_datasets(iris_data)

#how many instances
print('# instances in training set: ',len(train_ds))
print(' # instances in testing/validation set:', len(test_ds))

#create dataloaders - for training and validation/testing
train_loader = torch.utils.data.DataLoader(dataset=train_ds, batch_size = batch_size, shuffle = True)
test_loader = torch.utils.data.DataLoader(dataset=test_ds, batch_size = batch_size, shuffle = True)


# instances in training set:  120
 # instances in testing/validation set: 30
